---
# tasks file for ibm_installation_manager_install

- name: Create a directory if it does not exist
  file:
    path: /opt/IBM
    state: directory
    mode: '0755'

- name: download ibm installation manager
  get_url:
    url: "{{ ibmim_url }}"
    dest: /bin
    mode: 0755

- name: unzip installer
  unarchive:
    src: /bin/{{package}}
    dest: /etc
    remote_src: yes
- name: run command
  shell: ./installc -log log_file -acceptLicense
  args:
    chdir: /etc
