---
# tasks file for websphere
- name: install java sdk n was nd
  shell: ./imcl install {{ java_sdk_package }} {{ was_nd_package }} -repositories {{ java_sdk_url }},{{ was_nd_url }} -acceptLicense -installationDirectory /opt/IBM/WebSphere/AppServer 
  args:
    chdir: "{{ ibmim_tools_source }}"

